name: API Test Framework

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: 00 18 * * *

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean test -DSuite=suite -X
    - name: Upload a Build Artifact 
      uses: actions/upload-artifact@v5.0.0
      with:
        name: Logs
        path: logs/
